name: XCTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-ios:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install any dependencies
      - name: Install Dependencies
        run: swift package resolve

      # Run tests on iPhone 16 Simulator with iOS 26.0
      - name: Run Tests on iPhone 16 Simulator (iOS 26.0)
        run: |
          xcodebuild test \
            -scheme 'TestGithubActions' \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=26.0'
